apiVersion: v1
kind: Pod
metadata:
  name: postgres-client
spec:
  containers:
  - name: psql-client
    image: cloudyugacontregistry.azurecr.io/custom-postgres-restricted:latest
    command: ["/bin/bash", "-c", "while true; do sleep 30; done;"]
