apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsvp-default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsvp-default
  template:
    metadata:
      labels:
        app: rsvp-default
    spec:
      containers:
      - name: rsvp-default
        image: teamcloudyuga/rsvpapp
        env:
        - name: MONGODB_HOST
          value: mongodb
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          periodSeconds: 30
          timeoutSeconds: 1
          initialDelaySeconds: 50
        ports:
        - containerPort: 5000
          name: web-port    
---
apiVersion: v1
kind: Service
metadata:
  name: rsvp-default
  labels:
    app: rsvp-default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: web-port
    protocol: TCP
  selector:
    app: rsvp-default
