apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets-rsvp
  namespace: default
spec:
  provider: azure
  secretObjects:
  - secretName: rsvp-secrets
    type: Opaque
    data:
    - objectName: TEXT1
      key: TEXT1                        # Kubernetes secret key name
    - objectName: TEXT2
      key: TEXT2
    - objectName: COMPANY
      key: COMPANY
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "70922f50-fa04-4c85-b053-6ca9421398ac" # Managed identity client ID
    keyvaultName: "cy-key-vault-demo"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: TEXT1                   # Key vault secret name
          objectType: secret                  # The object type is secret
        - |
          objectName: TEXT2
          objectType: secret
        - |
          objectName: COMPANY
          objectType: secret
    tenantId: "409cc487-acdc-4acc-bd19-d00b0749befa" # Your Azure AD Tenant ID
    # This enables syncing the secret from Key Vault to a Kubernetes secret
    syncSecret.enabled: "true"
