apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-app-without-secret
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating-app-without-secret
  template:
    metadata:
      labels:
        app: rating-app-without-secret
    spec:
      containers:
      - name: rating-app-without-secret
        image: pratikshahp/rating-app:latest # cloudyugacontregistry.azurecr.io/rating-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: ''
        - name: POSTGRES_DB
          value: postgres
        - name: POSTGRES_HOST
          value: postgres-service # Ensure this is the correct service name for PostgreSQL in the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: rating-app-without-secret
  namespace: default
spec:
  selector:
    app: rating-app-without-secret
  ports:
    - protocol: TCP
      port: 80         # The port exposed externally
      targetPort: 5000 # The port that the rating-app container is listening on
  type: LoadBalancer   # Exposing the app through a LoadBalancer (for external access)
