apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-app-exp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating-app-exp
  template:
    metadata:
      labels:
        app: rating-app-exp
    spec:
      containers:
      - name: rating-app-exp
        image: cloudyugacontregistry.azurecr.io/rating-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_HOST
          value: postgres-service # Ensure this is the correct service name for PostgreSQL in the cluster
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: rating-app-exp
  namespace: default
spec:
  selector:
    app: rating-app-exp
  ports:
    - protocol: TCP
      port: 80         # The port exposed externally
      targetPort: 5000 # The port that the rating-app container is listening on
  type: LoadBalancer   # Exposing the app through a LoadBalancer (for external access)
