apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets-postgres
  namespace: default
spec:
  provider: azure
  secretObjects:
  - secretName: postgres-secrets
    type: Opaque
    data:
      - objectName: POSTGRES-USER
        key: POSTGRES_USER
      - objectName: POSTGRES-PASSWORD
        key: POSTGRES_PASSWORD
      - objectName: POSTGRES-DB
        key: POSTGRES_DB
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "<Managed identity client ID>"
    keyvaultName: "cy-key-vault-demo"
    cloudName: ""
    objects: |
      array:
        - |
          objectName: POSTGRES-USER
          objectType: secret
        - |
          objectName:  POSTGRES-PASSWORD
          objectType: secret
        - |
          objectName:  POSTGRES-DB
          objectType: secret
    tenantId: "<Your Azure AD Tenant ID>"
    # This enables syncing the secret from Key Vault to a Kubernetes secret
    syncSecret.enabled: "true"
